version: '3.7'

services:
  db:
    container_name: postgres_api
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: api
    expose:
      - '5433'
    ports:
      - '5434:5434'
    command: -p 5434